---
meta:
  name:    bind9
  release: BIND9
  target:  sw
  url:     https://ci.starkandwayne.com

  initial_version: 0.2.0

  bosh-lite:
    target: https://10.58.111.44:25555
    username: (( vault "secret/bosh-lites/lite44/users/admin:username" ))
    password: (( vault "secret/bosh-lites/lite44/users/admin:password" ))
    cacert:   (( vault "secret/bosh-lites/lite44/certs:rootCA.pem" ))

  aws:
    access_key: (( vault "secret/aws/cfcommunity:access" ))
    secret_key: (( vault "secret/aws/cfcommunity:secret" ))

  git:
    name: Stark & Wayne CI Bot
    email: ci@starkandwayne.com

  github:
    owner:  cloudfoundry-community
    repo:   bind9-boshrelease
    branch: master
    private_key:  (( vault "secret/pipelines/shared/github:private" ))
    access_token: (( vault "secret/pipelines/shared/github:access_token" ))

  slack:
    webhook: (( vault "secret/pipelines/bind9-boshrelease/slack:webhook" ))
    channel: '#botspam'
    username:      starkandwayne-ci
    icon:          https://www.starkandwayne.com/assets/images/shield-blue-50x50.png
    blob_success:  '(( concat "$BUILD_PIPELINE_NAME: New version of $BUILD_JOB_NAME was detected, and updated in master. <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME| Cut a new release?>" ))'
    blob_failure:  '(( concat "$BUILD_PIPELINE_NAME: :airplane_arriving: <" meta.url "/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME| Failed to update the blob for $BUILD_JOB_NAME>" ))'
